---

### run with --check
- name: username compliance
  hosts: all
  #check_mode: yes
  gather_facts: false
  vars:
    comp_file_loc: list-users.txt
    
  


  tasks:
    - name: Get users IOS
      cisco.ios.ios_command:
        commands:
          - show run | i username
      register: user_check_ios
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Get users NXOS
      cisco.nxos.nxos_command:
        commands:
          - show run | i username
      register: user_check_nxos
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Get users ARISTA
      arista.eos.eos_command:
        commands:
          - show run | i username
      register: user_check_arista
      when: ansible_network_os == 'arista.eos.eos'

    - name: build list of users IOS
      delegate_to: localhost
      ansible.builtin.shell:
            cmd: "echo '+ {{ inventory_hostname }} has the following usernames: {{ user_check_ios.stdout_lines[0] | regex_findall('(?:username) ([^\\s]+)') | replace('[','') | replace(']','') }}'  >> {{ comp_file_loc }}"      
      when: ansible_network_os == 'cisco.ios.ios'

    - name: build list of users NXOS
      delegate_to: localhost
      ansible.builtin.shell:
            cmd: "echo '+ {{ inventory_hostname }} has the following usernames: {{ user_check_nxos.stdout_lines[0] | regex_findall('(?:username) ([^\\s]+)') | replace('[','') | replace(']','') }}'  >> {{ comp_file_loc }}"  
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: build list of users ARISTA
      delegate_to: localhost
      ansible.builtin.shell:
            cmd: "echo '+ {{ inventory_hostname }} has the following usernames: {{ user_check_arista.stdout_lines[0] | regex_findall('(?:username) ([^\\s]+)') | replace('[','') | replace(']','') }}'  >> {{ comp_file_loc }}"  
      when: ansible_network_os == 'arista.eos.eos'





