---

### run with --check
- name: username compliance
  hosts: all
  #check_mode: yes
  gather_facts: false


  tasks:

    - name: Remove all users except admin
      cisco.ios.ios_user:
        aggregate:
          - name: maruf
        purge: true
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Remove all users except admin
      cisco.nxos.nxos_user:
        aggregate:
          - name: maruf
        purge: true
      when: ansible_network_os == 'cisco.nxos.nxos'